### ISSUE TITLE
MON-1 - Add Baseline Code

### ISSUE THREAD

**Issue by debuggerboy** [debuggerboy/pymonitor#1]
Python Monitoring Tool based on SSH2-Python Library.

Added Baseline code 873b5c4aca87112d1d4a68b2f5aaeb0603e4fb61

**Comment by debuggerboy** [comment]
Running into an error: `[Errno 106] Transport endpoint is already connected`

```
(.venv) debuggerboy@cassandra:~/labs/python/monitor$ python mon.py 
6.92308%

[I 200807 03:41:40 sshadaptor:23] Exit status: 0
Traceback (most recent call last):
  File "mon.py", line 11, in <module>
    sshconn(ssh_hostname, ssh_username, ssh_password, mem_used_cmd)
  File "/home/debuggerboy/labs/python/monitor/sshadaptor.py", line 8, in sshconn
    sock.connect((host, 22))
OSError: [Errno 106] Transport endpoint is already connected
```

**Comment by debuggerboy** [comment]
Will adding `socket.close()` will help?

reference: https://docs.python.org/2/library/socket.html#socket.socket.close

**Comment by debuggerboy** [comment]
> Will adding `socket.close()` will help?
> 
> reference: https://docs.python.org/2/library/socket.html#socket.socket.close

No, it seems:

```
Calling close and shutdown have two different effects on the underlying socket.

The first thing to point out is that the socket is a resource in the underlying OS and multiple processes can have a handle for the same underlying socket.

When you call close it decrements the handle count by one and if the handle count has reached zero then the socket and associated connection goes through the normal close procedure (effectively sending a FIN / EOF to the peer) and the socket is deallocated.

The thing to pay attention to here is that if the handle count does not reach zero because another process still has a handle to the socket then the connection is not closed and the socket is not deallocated.

On the other hand calling shutdown for reading and writing closes the underlying connection and sends a FIN / EOF to the peer regardless of how many processes have handles to the socket. However, it does not deallocate the socket and you still need to call close afterward.
```

read : https://stackoverflow.com/questions/409783/socket-shutdown-vs-socket-close

**Comment by debuggerboy** [comment]
Resolved the issues with `OSError: [Errno 106] Transport endpoint is already connected`

commit : cd10169 

Marking as resolved
